# Permalinks
permalink: /:title/

# Setup
title: Brack.io
tagline: Thoughts, stories and ideas
description: ''
url: https://dbrack.github.io
baseurl: ''
paginate: 5

# Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# About/contact
author:
  name: Dominik Brack
  email: me@brack.io
  twitter: https://twitter.com/_bracky
  github: https://github.com/dbrack

# Custom vars
version: 1.1.1
github:
  repo: https://github.com/dbrack/dbrack.github.io
analytics_id: UA-78462310-1
disqus: thedig

# Gems
gems:
  - jekyll-paginate # pagination
  - jekyll-gist # liquid tag for github gists
