# Permalinks
#
permalink: /:title/

gems:
  - jekyll-paginate # pagination

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Setup
title: The-Dig
tagline: 'Thoughts, stories and ideas'
description: ''
url: https://dbrack.github.io
baseurl: ''
paginate: 5

# About/contact
author:
  name: Dominik Brack
  url: https://twitter.com/_bracky

# Custom vars
version: 1.0.0
